"""Validate our analysis pipeline against 2607.07066's PUBLISHED trained weights.

No training, no GPU. If our transforms and sparsity metrics are right, they should
reproduce the qualitative picture the paper reports for n=165 from their own checkpoint.
"""
import numpy as np, torch, sys
from math import gcd
from src.tasks.algebra import describe, units
from src.analysis.transforms import unit_index, additive_dft, energy
from src.analysis.sparsity import gini, participation_ratio, key_freqs_5x_median

N = 165
_CK = "reference/interpreting-monoids/experiments/P165_d128_h4_mlp512_s1.pt"
try:
    ck = torch.load(_CK, map_location="cpu", weights_only=False)
except FileNotFoundError:   # reference/ is not shipped; reproduce.sh promises a clean skip
    print(f"{_CK} missing -- clone the authors' repositories into reference/ to run these cross-checks")
    sys.exit(0)
sd = ck["model_state_dict"] if "model_state_dict" in ck else ck
W = sd["embed.weight"].numpy()[:N].astype(float)
W = W - W.mean(0, keepdims=True)
print(f"their n={N} checkpoint: seed={ck.get('seed')}, W_E {W.shape}, "
      f"{len(ck.get('losses', []))} logged losses, final loss {ck['losses'][-1]:.2e}")

d = describe(N)
print(f"n=165: {d['factorization']}, phi={d['phi']}, {d['n_jclasses']} J-classes, "
      f"{d['n_nonregular']} non-regular, unit group factors {unit_index(N)[1]}")


def freq_norms(M, m):
    """2606.17399 Step 1 protocol: combined sin/cos norm per frequency, DC dropped."""
    k = np.arange(1, m // 2 + 1)[:, None]; t = np.arange(m)[None, :]
    s = np.sin(2 * np.pi * k * t / m) @ M
    c = np.cos(2 * np.pi * k * t / m) @ M
    return np.sqrt((s ** 2).sum(1) + (c ** 2).sum(1))


# --- 1. their own claim: embeddings organize by J-class ---
print("\n[1] J-class organization of the embedding (their central claim)")
lab = np.array([gcd(x, N) for x in range(N)])
cent = {d_: W[lab == d_].mean(0) for d_ in np.unique(lab)}
within = np.mean([np.linalg.norm(W[i] - cent[lab[i]]) for i in range(N)])
between = np.mean([np.linalg.norm(cent[a] - cent[b])
                   for a in cent for b in cent if a < b])
print(f"    mean within-J-class distance  = {within:.3f}")
print(f"    mean between-J-class distance = {between:.3f}")
print(f"    separation ratio (between/within) = {between/within:.2f}  "
      f"{'-> classes ARE separated' if between/within > 1 else '-> no separation'}")
# control: same class sizes, random assignment
rng = np.random.default_rng(0); sh = rng.permutation(lab)
cs = {d_: W[sh == d_].mean(0) for d_ in np.unique(sh)}
w2 = np.mean([np.linalg.norm(W[i] - cs[sh[i]]) for i in range(N)])
b2 = np.mean([np.linalg.norm(cs[a] - cs[b]) for a in cs for b in cs if a < b])
print(f"    shuffled-label control ratio      = {b2/w2:.2f}")

# --- 2. our two-basis result, on their weights ---
print("\n[2] Two-basis sparsity on THEIR weights (our Entry-3 finding)")
idx, orders, _ = unit_index(N)
U = np.array(sorted(idx, key=lambda x: idx[x]))
fn_add = freq_norms(W, N)
print(f"    additive     Gini={gini(fn_add):.3f}  IPR={participation_ratio(fn_add):.1f}  "
      f"key={[k+1 for k in key_freqs_5x_median(fn_add)]}")
e_mult = energy(__import__('src.analysis.transforms', fromlist=['x']).character_transform(W, N))
# Gini on amplitude (the protocol), PR on energy. An earlier version took the Gini of
# the energy spectrum and printed 0.884 (correction P6).
from analyze_n7 import mult_amplitude, rand_amplitude
print(f"    multiplicative (product-character) Gini={gini(mult_amplitude(W, N)):.3f}  "
      f"PR={participation_ratio(e_mult):.2f}")
print(f"    random orthogonal control          Gini={gini(rand_amplitude(W, N)):.3f}")
print(f"    zero-divisor density = {d['zero_divisors']/N:.3f}")

# --- 3. the key additive frequencies look like the divisor-dual lattice. Test it. ---
print("\n[3] PREDICTION: key additive frequencies are the multiples of n/p, for p | n")
from sympy import factorint
def predict(n):
    """A function supported on multiples of d is additively Fourier-supported on
    multiples of n/d. The J-class stratification is generated by the CRT components,
    i.e. the maximal prime powers q || n, so the predicted key additive frequencies are
    the multiples of n/q, up to n/2."""
    duals = {n // (p ** e) for p, e in factorint(n).items()}   # maximal prime powers = CRT components
    return sorted({m for d in duals for m in range(d, n // 2 + 1, d)})

def observed(W, n):
    return [k + 1 for k in key_freqs_5x_median(freq_norms(W, n))]

print(f"{'n':>5} {'factorization':>12} {'predicted (mult. of n/q, q||n)':>34} {'observed':>34} {'match':>7}")
cases = [("their ckpt", N, W)]
for n in [113, 121, 125, 119, 165, 120]:
    Ws = np.load(f"results/k01_scout/scout_n{n}_seed0.npz")["W_E"][:n].astype(float)
    cases.append(("scout", n, Ws - Ws.mean(0, keepdims=True)))
for tag, n, M in cases:
    p, o = predict(n), observed(M, n)
    ok = "EXACT" if p == o else ("subset" if set(o) <= set(p) else "no")
    fac = "*".join(f"{q}^{e}" if e > 1 else str(q) for q, e in sorted(factorint(n).items()))
    print(f"{n:>5} {fac:>12} {str(p)[:34]:>34} {str(o)[:34]:>34} {ok:>7}  [{tag}]")


# ============================================================================
# Cross-checks against the authors' published implementations.
#
# Both functions below are transcribed verbatim from the authors' released code
# (reference/ is not tracked; clone the authors' repositories there to re-check).
# ============================================================================
import os

print("\n[4] Sparsity conventions vs 2606.17399's own notebook  (this closed O1)")
_dlc = "reference/Discrete-Log-Clock/multiplication_grokking.ipynb"
if not os.path.exists(_dlc):
    print("    reference/Discrete-Log-Clock missing -- run scripts/restore_external.sh")
else:
    # verbatim from multiplication_grokking.ipynb, cell "Define reusable sparsity metrics"
    def their_gini(x):
        x = np.sort(np.abs(np.asarray(x, dtype=np.float64)))
        m = len(x); i = np.arange(1, m + 1, dtype=np.float64)
        return float(((2 * i - m - 1) * x).sum() / (m * x.sum()))

    def their_ipr(x):
        x = np.abs(np.asarray(x, dtype=np.float64)); x2 = x ** 2
        return float((x2.sum() ** 2) / (x2 ** 2).sum())

    # Their IPR squares the AMPLITUDE it is handed, so it is a participation ratio on
    # ENERGY. Ours took amplitude directly -- that one line was open question O1.
    _a = np.array([3.0, 1.0, 0.5, 0.2, 0.1])
    assert abs(their_ipr(_a) - participation_ratio(_a ** 2)) < 1e-9, \
        "their IPR must equal our participation_ratio on ENERGY"
    assert abs(their_gini(_a) - gini(_a)) < 1e-9, \
        "their Gini must equal our gini on AMPLITUDE"
    print("    their IPR(amplitude)  == our participation_ratio(energy)     OK")
    print("    their Gini(amplitude) == our gini(amplitude)                 OK")
    print("    => Gini on amplitude, participation ratio on ENERGY. See LAB_NOTEBOOK Entry 16.")

print("\n[5] stablemax vs 2501.04697's reference implementation  (C13)")
_pri = "reference/grokking-at-the-edge-of-numerical-stability/utils.py"
if not os.path.exists(_pri):
    print("    reference/grokking-at-the-edge-of-numerical-stability missing -- "
          "run scripts/restore_external.sh")
else:
    import torch
    from src.autograd.engine import Tensor
    from src.autograd.nn import stablemax_cross_entropy

    def _s(x, epsilon=1e-30):                       # verbatim, utils.py:20
        return torch.where(x < 0, 1 / (1 - x + epsilon), x + 1)

    def _their_sce(logits, labels):                 # verbatim, utils.py:27,32
        sx = _s(logits.to(torch.float64))
        lp = torch.log(sx / torch.sum(sx, dim=-1, keepdim=True))
        return -torch.mean(torch.gather(lp, index=labels[:, None], dim=-1))

    rng = np.random.default_rng(0)
    worst = 0.0
    for scale in (1.0, 10.0, 100.0, 1000.0):
        L = rng.normal(0, scale, size=(64, 17)); y = rng.integers(0, 17, size=64)
        ours = float(stablemax_cross_entropy(Tensor(L.copy()), y).data)
        theirs = _their_sce(torch.tensor(L, dtype=torch.float64), torch.tensor(y)).item()
        worst = max(worst, abs(ours - theirs))
        print(f"    logit scale {scale:6.0f}:  ours {ours:.12f}  theirs {theirs:.12f}  "
              f"|diff| {abs(ours - theirs):.1e}")
    assert worst < 1e-12, f"stablemax disagrees with the reference at {worst:.2e}"
    print(f"    max |diff| {worst:.1e} over 4 logit scales -- machine precision      OK")
