"""scripts/reproduce.sh must cover every claim-carrying script. A guard, not documentation.

`scripts/reproduce.sh` is the single entry point that re-runs everything from a bare
clone. A script added without a line there would silently fall out of reproduction, so
this fails the self-check suite instead.

  PYTHONPATH=. .venv/bin/python test_reproduce.py
"""
import glob, re
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SH = os.path.join(ROOT, "scripts", "reproduce.sh")

# Scripts deliberately not run by reproduce.sh, each with the reason. Adding a name here is
# a decision to be defended in review, which is the point of making it explicit.
EXEMPT = {
    "run_gate1.py":  "trains a model -- Gate 1 is re-run by hand, not by the entry point",
    "run_n7.py":     "a 21-hour sweep; relaunched via scripts/run_n7_all.sh",
    "test_gate1.py": "asserts against results/gate1, which is regenerated by run_gate1.py",
}


def main():
    body = open(SH).read()
    scripts = {os.path.basename(p) for p in
               glob.glob(os.path.join(ROOT, "analyze_*.py"))
               + glob.glob(os.path.join(ROOT, "test_*.py"))
               + glob.glob(os.path.join(ROOT, "run_*.py"))
               + [os.path.join(ROOT, "jclass_spectra.py"), os.path.join(ROOT, "refcheck.py")]}
    scripts.discard(os.path.basename(__file__))
    missing = sorted(s for s in scripts if s not in EXEMPT and s not in body)
    assert all(re.search(rf"^\s*scripts/lean_gate\.sh{a}(\s+#.*)?$", body, re.M)
               for a in (" --selfcheck", "")), \
        "scripts/reproduce.sh does not run the Lean gate and its selfcheck"
    stale = sorted(s for s in EXEMPT if s not in scripts)
    assert not missing, (
        "scripts/reproduce.sh does not cover: " + ", ".join(missing) +
        "\nAdd each one, or add it to EXEMPT here with the reason.")
    assert not stale, f"EXEMPT names scripts that no longer exist: {stale}"
    print(f"test_reproduce PASS  {len(scripts)-len(EXEMPT)} claim-carrying scripts covered, "
          f"{len(EXEMPT)} exempt with reasons")


if __name__ == "__main__":
    main()
